export default {
  pages: [
    "pages/index/index",
    "pages/general/index",
    "pages/general/font/index",
    "pages/dataEntry/index",
    "pages/feedback/index",
    "pages/dataDisplay/index",
    "pages/navigation/index",
    "pages/animate/index",
    "components/badge/demo/index",
    "components/button/demo/index",
    "components/color/demo/index",
    "components/countdown/demo/index",
    "components/tag/demo/index",
    "components/icon/demo/index",
    "components/radio/demo/index",
    "components/navBar/demo/index",
    "components/tabbar/demo/index",
    "components/checkbox/demo/index",
    "components/switch/demo/index",
    "components/list/demo/index",
    "components/input/demo/index",

    "components/rate/demo/index",
    "components/stepper/demo/index",
    "components/loading/demo/index",
    "components/tabs/demo/index",
    "components/search/demo/index",
    "components/toast/demo/index",
    "components/carousel/demo/index",
    "components/modal/demo/index",
    "components/actionsheet/demo/index",
    "components/swipeCell/demo/index",
    "components/layout/demo/index",
    "components/upload/demo/index",
    "components/imagePreview/demo/index",
    "components/picker/demo/index",
    "components/datePicker/demo/index",
    "components/noticeBar/demo/index",
    "components/animate/demo/index",

    "pages/loki/index",
    "pages/loki/turntable/index",
    "pages/loki/ninegrid/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black",
  },
};
