# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
          version: 6

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - run: pnpm start
#     - run: pnpm test

    - name: Build OSSA && loki
      run: pnpm build
      
    - name: Build Demo
      run: pnpm build:demo --if-present
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-page
        folder: packages/ossa-demo/dist
        clean-exclude: pr-preview/

    - name: Sleep to make sure page gets updated
      run: sleep 1m
      shell: bash

    - name: e2e test
      run: pnpm test -- -- --config baseUrl=https://neteaseyanxuan.github.io/OSSA --record --key cdc63db7-73cb-463b-9b7c-4360235ece96

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        retention-days: 1
        path: |
          packages/ossa-demo/test/e2e/screenshots
